PmeetLabs/pmeet-server

- build.gradle.kts
- docker-compose.yml
- src/main/kotlin/pmeet/pmeetserver/config/RedisConfig.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/UserService.kt
- src/main/resources/application.yml
resolves #14
- (key, val) -> (String, String) 지원
- refreshToken 생성이 아직 없으므로 임시로 key 설정
- 
-
> feat: redis 연결

- build.gradle.kts
- src/main/kotlin/pmeet/pmeetserver/common/exception/GlobalExceptionHandler.kt
- src/main/kotlin/pmeet/pmeetserver/common/utils/jwt/JwtUtil.kt
- src/main/kotlin/pmeet/pmeetserver/common/utils/jwt/RefreshTokenUtil.kt
- src/main/kotlin/pmeet/pmeetserver/user/controller/AuthController.kt
- src/main/kotlin/pmeet/pmeetserver/user/domain/auth/RefreshTokenMap.kt
- src/main/kotlin/pmeet/pmeetserver/user/dto/response/UserJwtDto.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/UserFacadeService.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/UserService.kt
로그인 시 토큰 반환(access token 3시간, refresh token 2주)
- 
-
> feat: 로그인 서비스에 토큰 발급 추가

- docker-compose.yml
- src/main/kotlin/pmeet/pmeetserver/common/ErrorCode.kt
- src/main/kotlin/pmeet/pmeetserver/user/controller/AuthController.kt
- src/main/kotlin/pmeet/pmeetserver/user/domain/User.kt
- src/main/kotlin/pmeet/pmeetserver/user/dto/request/SetPasswordRequestDto.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/UserFacadeService.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/UserService.kt
- src/main/kotlin/pmeet/pmeetserver/user/validation/PasswordConfirmMatchValidator.kt
- src/main/kotlin/pmeet/pmeetserver/user/validation/annotation/PasswordConfirmMatch.kt
resolves #16
- 비밀번호 재설장 후 Update를 하였음
- docker-compose.yml 수정
- 비밀번호 확인 일치 여부를 위해 커스텀 Validator 생성
> feat: 비밀번호 재설정

- src/main/kotlin/pmeet/pmeetserver/user/dto/request/SignUpRequestDto.kt
> refac: 기획 변경에 따른 닉네임에 숫자 추가

- src/main/kotlin/pmeet/pmeetserver/config/SpringDocConfig.kt
> feat: swagger에 access token 입력 추가

- .gitignore
- build.gradle.kts
- src/main/kotlin/pmeet/pmeetserver/common/ErrorCode.kt
- src/main/kotlin/pmeet/pmeetserver/common/utils/jwt/JwtUtil.kt
- src/main/kotlin/pmeet/pmeetserver/common/utils/jwt/RefreshTokenUtil.kt
- src/main/kotlin/pmeet/pmeetserver/config/Authentication.kt
- src/main/kotlin/pmeet/pmeetserver/config/SecurityConfig.kt
- src/main/kotlin/pmeet/pmeetserver/user/controller/AuthController.kt
- src/main/kotlin/pmeet/pmeetserver/user/controller/UserController.kt
- src/main/kotlin/pmeet/pmeetserver/user/domain/User.kt
- src/main/kotlin/pmeet/pmeetserver/user/dto/response/UserSummaryResponseDto.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/UserFacadeService.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/UserService.kt
> SpringSecurity에 JWT Filter 연동 및 토큰 검증

- src/main/kotlin/pmeet/pmeetserver/common/ErrorCode.kt
- src/main/kotlin/pmeet/pmeetserver/common/utils/jwt/JwtUtil.kt
- src/main/kotlin/pmeet/pmeetserver/config/Authentication.kt
- src/main/kotlin/pmeet/pmeetserver/config/SecurityConfig.kt
- 토큰 검증 시 토큰이 만료되었을 경우 만료 메시지
- 토큰 검증 시 만료 이외의 에러는 모든 유효하지 않은 토큰으로 간주
- 
-
> feat: 유저 인증 관련 에러 반환

- src/main/kotlin/pmeet/pmeetserver/user/controller/AuthController.kt
- src/main/kotlin/pmeet/pmeetserver/user/dto/request/CheckMailRequestDto.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/UserFacadeService.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/UserService.kt
> feat: 메일 중복 체크 api

- src/main/kotlin/pmeet/pmeetserver/auth/service/EmailService.kt
- src/main/kotlin/pmeet/pmeetserver/config/SecurityConfig.kt
> feat: cors 설정

- src/main/kotlin/pmeet/pmeetserver/config/SecurityConfig.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/UserFacadeService.kt
- 유저 생성 서비스 진입 시 이메일 인증 여부 체크
- cors 설정 변경
> feat: 회원가입 시 이메일 인증 확인

- build.gradle.kts
- src/main/kotlin/pmeet/pmeetserver/config/SecurityConfig.kt
- src/test/kotlin/pmeet/pmeetserver/config/MongoTestConfig.kt
- src/test/kotlin/pmeet/pmeetserver/user/repository/UserRepositoryUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/service/UserServiceUnitTest.kt
> feat: userService unit test

- src/main/kotlin/pmeet/pmeetserver/config/MongoConfig.kt
- src/test/kotlin/pmeet/pmeetserver/config/ProjectConfig.kt
- src/test/kotlin/pmeet/pmeetserver/user/repository/UserRepositoryUnitTest.kt
> mongodb를 Spring Bean에 등록하는 설정 추가

- src/test/kotlin/pmeet/pmeetserver/user/service/UserFacadeServiceUnitTest.kt
* userFacadeServiceUnitTest 작성
* 다른 서비스에서 발생하는 Exception Test 작성 안함, userFacadeService에서 직접 발생시키는 Exception만 작성
- 
-
> test: UserFacadeService 단위 테스트 작성

- src/test/kotlin/pmeet/pmeetserver/user/UserIntegrationTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/repository/UserRepositoryUnitTest.kt
> feat: user integration test

- src/test/kotlin/pmeet/pmeetserver/config/TestSecurityConfig.kt
- src/test/kotlin/pmeet/pmeetserver/user/controller/AuthControllerUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/controller/UserControllerUnitTest.kt
- csrf와 formLogin Disable을 위해 Test용 SecurityConfig 생성
- queryParameter 매핑은 UriBuilder 사용
- 
-
> test: AuthController Unit Test

- src/test/kotlin/pmeet/pmeetserver/user/UserIntegrationTest.kt
MongoDB IO 작업 불가 이슈 해결을 위해 Dispatcher.IO 사용
- 
-
> fix: Integration 테스트 미실행 이슈 해결을 위해 Dispatcher 변경

- src/main/kotlin/pmeet/pmeetserver/user/controller/AuthController.kt
- src/main/kotlin/pmeet/pmeetserver/user/controller/UserController.kt
- src/main/kotlin/pmeet/pmeetserver/user/domain/User.kt
- src/main/kotlin/pmeet/pmeetserver/user/domain/enum/Gender.kt
- src/main/kotlin/pmeet/pmeetserver/user/dto/response/UserResponseDto.kt
- src/main/kotlin/pmeet/pmeetserver/user/dto/response/UserSignUpResponseDto.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/UserFacadeService.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/mail/EmailService.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/oauth/GoogleOauthService.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/oauth/KakaoOauthService.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/oauth/NaverOauthService.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/oauth/OauthFacadeService.kt
- src/test/kotlin/pmeet/pmeetserver/user/UserIntegrationTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/controller/AuthControllerUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/service/UserFacadeServiceUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/service/mail/EmailServiceUnitTest.kt
> feat: 유저 상세 조회

- src/main/kotlin/pmeet/pmeetserver/user/controller/UserController.kt
- src/main/kotlin/pmeet/pmeetserver/user/domain/User.kt
- src/main/kotlin/pmeet/pmeetserver/user/dto/request/UpdateUserRequestDto.kt
- src/main/kotlin/pmeet/pmeetserver/user/dto/response/UserResponseDto.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/UserFacadeService.kt
- src/test/kotlin/pmeet/pmeetserver/user/UserIntegrationTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/service/UserFacadeServiceUnitTest.kt
> feat: User update api

- src/main/kotlin/pmeet/pmeetserver/common/ErrorCode.kt
- src/main/kotlin/pmeet/pmeetserver/common/exception/BadRequestException.kt
- src/main/kotlin/pmeet/pmeetserver/user/controller/UserController.kt
- src/main/kotlin/pmeet/pmeetserver/user/domain/User.kt
- src/main/kotlin/pmeet/pmeetserver/user/repository/UserRepository.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/UserFacadeService.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/UserService.kt
- src/test/kotlin/pmeet/pmeetserver/user/UserIntegrationTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/repository/UserRepositoryUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/service/UserFacadeServiceUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/service/UserServiceUnitTest.kt
resolves #27 
- Soft Delete를 위한 Flag 속성 추가와 조회 기능에 대해서 Deleted가 True인 경우를 제외하도록 하였음
- user 엔티티에 isDeleted 필드 추가
- userService의 getUserById 로직에 isDeleted 체크 추가
- BadRequestException 추가
- Repository의 findBy 메서드에 isDeletedFalse 추가
> feat: 유저 회원 탈퇴

- .github/workflows/gradle.yml
- src/main/resources/application-test.yml
- src/main/resources/application.yml
- src/test/resources/application.yml
- #71 
PR 시, 자동으로 main 브랜치에 대한 테스트 수행하도록 구성
- github gradle.yml 추가
> 📦 ci: pr 시, 자동으로 test 수행하고 결과 reporting 하도록 구성

- src/main/kotlin/pmeet/pmeetserver/common/ErrorCode.kt
- src/main/kotlin/pmeet/pmeetserver/user/controller/ResumeController.kt
- src/main/kotlin/pmeet/pmeetserver/user/domain/enum/ExperienceYear.kt
- src/main/kotlin/pmeet/pmeetserver/user/domain/resume/Resume.kt
- src/main/kotlin/pmeet/pmeetserver/user/dto/resume/request/CreateResumeRequestDto.kt
- src/main/kotlin/pmeet/pmeetserver/user/dto/resume/response/ResumeResponseDto.kt
- src/main/kotlin/pmeet/pmeetserver/user/repository/resume/ResumeRepository.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/resume/ResumeFacadeService.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/resume/ResumeService.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/ResumeGenerator.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/ResumeIntegrationTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/controller/ResumeControllerUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/repository/ResumeRepositoryUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/service/ResumeServiceUnitTest.kt
resolves #58 
- ✨ feat: 이력서 저장 및 단건 조회 기능 개발 및 테스트 완료
> ✨ feat: 이력서 저장 및 단건 조회 기능 개발

- src/main/kotlin/pmeet/pmeetserver/common/ErrorCode.kt
- src/main/kotlin/pmeet/pmeetserver/user/controller/ResumeController.kt
- src/main/kotlin/pmeet/pmeetserver/user/domain/resume/Resume.kt
- src/main/kotlin/pmeet/pmeetserver/user/dto/resume/request/ResumeCommonDtos.kt
- src/main/kotlin/pmeet/pmeetserver/user/dto/resume/request/UpdateResumeRequestDto.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/resume/ResumeFacadeService.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/resume/ResumeService.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/ResumeGenerator.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/controller/ResumeControllerUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/service/ResumeServiceUnitTest.kt
resolves #59 
- 🧪 test: 이력서 수정 단위 테스트 선작성
- ✨ feat: 이력서 수정 기능 개발
> ✨ feat: 이력서 수정 기능 개발

- .github/workflows/cd.yml
- build.gradle.kts
resolves #90 
- bootjar에 의해 생성된 jar만 사용 ( jar에 의해 생성된 jar 사용 X)
- github secret 사용하여 보안
- 백엔드 host 서버에 script 추가하여 deploy 실행(기존 프로세스 종료 및 jar 재실행) -> 추후 컨테이너 환경으로 변경
- 
-
> feat: CD setting

- src/main/kotlin/pmeet/pmeetserver/common/ErrorCode.kt
- src/main/kotlin/pmeet/pmeetserver/user/controller/ResumeController.kt
- src/main/kotlin/pmeet/pmeetserver/user/domain/resume/Resume.kt
- src/main/kotlin/pmeet/pmeetserver/user/dto/resume/request/CopyResumeRequestDto.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/resume/ResumeFacadeService.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/ResumeGenerator.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/ResumeIntegrationTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/controller/ResumeControllerUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/service/ResumeFacadeServiceUnitTest.kt
resolves  #61 
✨ feat: 이력서 복사 기능 구현
> ✨ feat: 이력서 복사 기능 구현

- src/main/kotlin/pmeet/pmeetserver/common/ErrorCode.kt
- src/main/kotlin/pmeet/pmeetserver/user/controller/ResumeController.kt
- src/main/kotlin/pmeet/pmeetserver/user/dto/resume/request/ChangeResumeAvtiveRequestDto.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/resume/ResumeFacadeService.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/resume/ResumeService.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/ResumeGenerator.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/ResumeIntegrationTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/controller/ResumeControllerUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/service/ResumeFacadeServiceUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/service/ResumeServiceUnitTest.kt
resolves #62 
- ✨ feat: 이력서 프미팅 게시 기능 구현
- ✨ feat: 이력서 프미팅 게시 기능 구현
> ✨ feat: 이력서 프미팅 게시 기능 구현

- src/main/kotlin/pmeet/pmeetserver/common/ErrorCode.kt
- src/main/kotlin/pmeet/pmeetserver/project/controller/ProjectCommentController.kt
- src/main/kotlin/pmeet/pmeetserver/project/domain/ProjectComment.kt
- src/main/kotlin/pmeet/pmeetserver/project/dto/request/comment/CreateProjectCommentRequestDto.kt
- src/main/kotlin/pmeet/pmeetserver/project/dto/request/comment/ProjectCommentResponseDto.kt
- src/main/kotlin/pmeet/pmeetserver/project/repository/ProjectCommentRepository.kt
- src/main/kotlin/pmeet/pmeetserver/project/repository/ProjectRepository.kt
- src/main/kotlin/pmeet/pmeetserver/project/service/ProjectCommentService.kt
- src/main/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeService.kt
- src/main/kotlin/pmeet/pmeetserver/project/service/ProjectService.kt
- src/test/kotlin/pmeet/pmeetserver/project/ProjectCommentIntegrationTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/controller/ProjectCommentControllerUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/service/ProjectCommentServiceUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeServiceUnitTest.kt
resolves #101 
- ProjectCommentController 분리(project의 하위의 resource로 바라보지 않고 분리하고 projectid를 requestbody로 넘김)
- ProjectFacadeService 공유(Comment용이 필요할 거 같지 않다고 생각됨)
- Embedding을 사용할지 Reference를 사용할지 고민되는 부분 (현재는 Reference)
- 
-
> feat: 댓글 생성

- src/main/kotlin/pmeet/pmeetserver/user/controller/ResumeController.kt
- src/main/kotlin/pmeet/pmeetserver/user/domain/resume/Resume.kt
- src/main/kotlin/pmeet/pmeetserver/user/repository/resume/ResumeRepository.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/resume/ResumeFacadeService.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/resume/ResumeService.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/ResumeGenerator.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/ResumeIntegrationTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/controller/ResumeControllerUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/repository/ResumeRepositoryUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/service/ResumeFacadeServiceUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/service/ResumeServiceUnitTest.kt
resolves #82 
✨ feat: 본인 소유 이력서 목록 조회 기능 구현
- ✨ feat: 본인 소유 이력서 목록 조회 기능 구현
> ✨ feat: 본인 소유 이력서 목록 조회 기능 구현

- src/main/kotlin/pmeet/pmeetserver/common/ErrorCode.kt
- src/main/kotlin/pmeet/pmeetserver/project/controller/ProjectCommentController.kt
- src/main/kotlin/pmeet/pmeetserver/project/domain/ProjectComment.kt
- src/main/kotlin/pmeet/pmeetserver/project/dto/request/comment/ProjectCommentResponseDto.kt
- src/main/kotlin/pmeet/pmeetserver/project/repository/ProjectCommentRepository.kt
- src/main/kotlin/pmeet/pmeetserver/project/service/ProjectCommentService.kt
- src/main/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeService.kt
- src/test/kotlin/pmeet/pmeetserver/project/ProjectCommentIntegrationTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/controller/ProjectCommentControllerUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/service/ProjectCommentServiceUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeServiceUnitTest.kt
resolves #103 
- "작성자가 삭제한 댓글입니다" 표기를 위해 soft delete 적용
- 
-
> feat: 댓글 삭제 

- src/main/kotlin/pmeet/pmeetserver/project/domain/Project.kt
- src/main/kotlin/pmeet/pmeetserver/project/domain/ProjectComment.kt
- src/main/kotlin/pmeet/pmeetserver/user/domain/User.kt
- src/main/kotlin/pmeet/pmeetserver/user/domain/job/Job.kt
- src/main/kotlin/pmeet/pmeetserver/user/domain/resume/Resume.kt
- src/main/kotlin/pmeet/pmeetserver/user/domain/techStack/TechStack.kt
- src/test/kotlin/pmeet/pmeetserver/project/ProjectCommentIntegrationTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/UserIntegrationTest.kt
> refac: 범용성을 위해 id val -> var로 변경

- src/main/kotlin/pmeet/pmeetserver/project/controller/ProjectController.kt
- src/main/kotlin/pmeet/pmeetserver/project/dto/response/ProjectWithUserResponseDto.kt
- src/main/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeService.kt
- src/main/kotlin/pmeet/pmeetserver/user/dto/response/UserResponseDtoInProject.kt
- src/test/kotlin/pmeet/pmeetserver/project/ProjectIntegrationTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/controller/ProjectControllerUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeServiceUnitTest.kt
resolves #100 
✨ feat: 프밋 단건 조회 기능 구현
- ✨ feat: 프밋 단건 조회 기능 구현
-
> ✨ feat: 프밋 단건 조회 기능 구현

- src/main/kotlin/pmeet/pmeetserver/project/repository/ProjectTryoutRepository.kt
- src/main/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeService.kt
- src/main/kotlin/pmeet/pmeetserver/project/service/ProjectTryoutService.kt
- src/test/kotlin/pmeet/pmeetserver/project/ProjectIntegrationTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/repository/ProjectCommentRepositoryUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/repository/ProjectTryoutRepositoryUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeServiceUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/service/ProjectTryoutServiceUnitTest.kt
resolves #122 
- 프밋 모집 게시글 삭제 시 지원서들 일괄 삭제
> feat: 프밋 모집 게시글 삭제 시 받았던 지원서 삭제

- src/main/kotlin/pmeet/pmeetserver/project/repository/CustomProjectRepositoryImpl.kt
> 🚀 deploy 2024.08.05

- src/main/kotlin/pmeet/pmeetserver/project/repository/CustomProjectRepositoryImpl.kt
> 🚀 deploy 2024.08.05 no.2

- src/main/kotlin/pmeet/pmeetserver/user/domain/resume/Resume.kt
- src/main/kotlin/pmeet/pmeetserver/user/dto/resume/response/ResumeResponseDto.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/ResumeGenerator.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/ResumeIntegrationTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/service/ResumeFacadeServiceUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/service/ResumeServiceUnitTest.kt
- resolves #58 
- resolves #59 
-  ✨ feat: 이력서에 생성일자 및 수정일 필드 추가
> ✨ feat: 이력서에 생성일자 및 수정일 필드 추가

- src/main/kotlin/pmeet/pmeetserver/project/dto/response/ProjectWithUserResponseDto.kt
- src/test/kotlin/pmeet/pmeetserver/project/ProjectIntegrationTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/controller/ProjectControllerUnitTest.kt
resolves #100
- ✨ feat: 프로젝트 단건 상세 조회에 모집 인원 정보 필드 추가
-
> ✨ feat: 프로젝트 단건 상세 조회에 모집 인원 정보 필드 추가

- src/main/kotlin/pmeet/pmeetserver/project/dto/response/ProjectWithUserResponseDto.kt
- src/main/kotlin/pmeet/pmeetserver/user/domain/resume/Resume.kt
- src/main/kotlin/pmeet/pmeetserver/user/dto/resume/response/ResumeResponseDto.kt
- src/test/kotlin/pmeet/pmeetserver/project/ProjectIntegrationTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/controller/ProjectControllerUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/ResumeGenerator.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/ResumeIntegrationTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/service/ResumeFacadeServiceUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/service/ResumeServiceUnitTest.kt
> 🚀 deploy 2024.08.06 no.1

- README.md
📝 docs: repository description 추가
- 더 추가되면 좋을 항목 있을지 의견 부탁드립니다.
> 📝 docs: repository description 추가

- src/main/kotlin/pmeet/pmeetserver/common/ErrorCode.kt
- src/main/kotlin/pmeet/pmeetserver/project/controller/ProjectTryoutController.kt
- src/main/kotlin/pmeet/pmeetserver/project/repository/ProjectTryoutRepository.kt
- src/main/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeService.kt
- src/main/kotlin/pmeet/pmeetserver/project/service/ProjectTryoutService.kt
- src/test/kotlin/pmeet/pmeetserver/project/ProjectTryoutIntegrationTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/controller/ProjectTryoutControllerUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/repository/ProjectTryoutRepositoryUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeServiceUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/service/ProjectTryoutServiceUnitTest.kt
resolves #128 
✨ feat: 프밋에 대한 지원자 목록 조회
> ✨ feat: 프밋에 대한 지원자 목록 조회

- src/main/kotlin/pmeet/pmeetserver/file/service/FileFacadeService.kt
- src/main/kotlin/pmeet/pmeetserver/file/service/FileService.kt
> 🚀 deploy 2024.08.15 no.2

- src/main/kotlin/pmeet/pmeetserver/user/controller/ResumeController.kt
- src/main/kotlin/pmeet/pmeetserver/user/domain/User.kt
- src/main/kotlin/pmeet/pmeetserver/user/domain/resume/Resume.kt
- src/main/kotlin/pmeet/pmeetserver/user/dto/resume/response/BookmarkedResumeResponseDto.kt
- src/main/kotlin/pmeet/pmeetserver/user/repository/resume/ResumeRepository.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/resume/ResumeFacadeService.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/resume/ResumeService.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/ResumeGenerator.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/ResumeIntegrationTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/controller/ResumeControllerUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/repository/ResumeRepositoryUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/service/ResumeFacadeServiceUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/service/ResumeServiceUnitTest.kt
resolves #141
✨ feat: 프밋 북마크 추가, 해제, 조회 기능 개발
- ✨ feat: 프밋 북마크 추가, 해제, 조회 기능 개발
> ✨ feat: 프밋 북마크 추가, 해제, 조회 기능 개발

- .github/workflows/ci.yml
- .github/workflows/publish_test.yml
📦 ci: pr 시, test 수행 결과를 자동으로 comment 남기도록 구성
> 📦 ci: pr 시, test 수행 결과를 자동으로 comment 남기도록 구성

- src/main/kotlin/pmeet/pmeetserver/project/controller/ProjectController.kt
- src/main/kotlin/pmeet/pmeetserver/project/dto/response/GetMyProjectResponseDto.kt
- src/main/kotlin/pmeet/pmeetserver/project/repository/CustomProjectRepository.kt
- src/main/kotlin/pmeet/pmeetserver/project/repository/CustomProjectRepositoryImpl.kt
- src/main/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeService.kt
- src/main/kotlin/pmeet/pmeetserver/project/service/ProjectService.kt
- src/test/kotlin/pmeet/pmeetserver/project/ProjectIntegrationTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/controller/ProjectControllerUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/repository/ProjectRepositoryUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeServiceUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/service/ProjectServiceUnitTest.kt
resolves #138 
- 내가 생성한 프밋 모집 게시글 슬라이스 조회
> feat: 내가 생성한 프밋 모집 Slice 조회

- src/main/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeService.kt
- src/main/kotlin/pmeet/pmeetserver/user/domain/enum/NotificationType.kt
- src/main/kotlin/pmeet/pmeetserver/user/domain/notification/Notification.kt
- src/main/kotlin/pmeet/pmeetserver/user/repository/notification/NotificationRepository.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/notification/NotificationService.kt
- src/test/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeServiceUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/notification/repository/NotificationRepositoryUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/notification/service/NotificationServiceUnitTest.kt
#173 
✨ feat: 알림 기능 구현
- 알림 조회 기능 개발
> ✨ feat: 알림 기능 구현

- .github/workflows/ci.yml
- .github/workflows/publish_test.yml
- build.gradle.kts
resolves #70
📦 ci: pr 시, jacoco 를 활용한 testCoverage comment 로 추가되도록 구현
https://creampuffy.tistory.com/193
> 📦 ci: pr 시, jacoco 를 활용한 testCoverage comment 로 추가되도록 구현

- src/main/kotlin/pmeet/pmeetserver/project/controller/ProjectTryoutController.kt
- src/main/kotlin/pmeet/pmeetserver/project/domain/ProjectTryout.kt
- src/main/kotlin/pmeet/pmeetserver/project/repository/ProjectTryoutRepository.kt
- src/main/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeService.kt
- src/main/kotlin/pmeet/pmeetserver/project/service/ProjectTryoutService.kt
- src/test/kotlin/pmeet/pmeetserver/project/ProjectTryoutIntegrationTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/controller/ProjectTryoutControllerUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/repository/ProjectTryoutRepositoryUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeServiceUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/service/ProjectTryoutServiceUnitTest.kt
- #137 
✨ feat: 프로젝트 참여자 목록 조회 기능 구현
-  ✨ feat: 프로젝트 참여자 목록 조회 기능 구현
> ✨ feat: 프로젝트 참여자 목록 조회 기능 구현

- src/main/kotlin/pmeet/pmeetserver/common/ErrorCode.kt
- src/main/kotlin/pmeet/pmeetserver/project/controller/ProjectController.kt
- src/main/kotlin/pmeet/pmeetserver/project/domain/Project.kt
- src/main/kotlin/pmeet/pmeetserver/project/domain/ProjectMember.kt
- src/main/kotlin/pmeet/pmeetserver/project/domain/ProjectTryout.kt
- src/main/kotlin/pmeet/pmeetserver/project/dto/request/CompleteProjectRequestDto.kt
- src/main/kotlin/pmeet/pmeetserver/project/dto/response/CompletedProjectResponseDto.kt
- src/main/kotlin/pmeet/pmeetserver/project/dto/response/ProjectWithTryoutResponseDto.kt
- src/main/kotlin/pmeet/pmeetserver/project/repository/ProjectMemberRepository.kt
- src/main/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeService.kt
- src/main/kotlin/pmeet/pmeetserver/project/service/ProjectMemberService.kt
- src/main/kotlin/pmeet/pmeetserver/project/service/ProjectService.kt
- src/main/kotlin/pmeet/pmeetserver/user/controller/ResumeController.kt
- src/main/kotlin/pmeet/pmeetserver/user/dto/resume/response/ResumeResponseDto.kt
- src/main/kotlin/pmeet/pmeetserver/user/repository/resume/CustomResumeRepository.kt
- src/main/kotlin/pmeet/pmeetserver/user/repository/resume/CustomResumeRepositoryImpl.kt
- src/main/kotlin/pmeet/pmeetserver/user/repository/resume/vo/ProjectMemberWithResume.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/resume/ResumeFacadeService.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/resume/ResumeService.kt
- src/test/kotlin/pmeet/pmeetserver/project/controller/ProjectControllerUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeServiceUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/ResumeGenerator.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/ResumeIntegrationTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/repository/ResumeRepositoryUnitTest.kt
resolves #139 
✨ feat: 프로젝트 완성 변경 요청 기능 구현## Changes detail
> ✨ feat: 프로젝트 완성 변경 요청 기능 구현

- src/main/kotlin/pmeet/pmeetserver/project/controller/ProjectController.kt
- src/main/kotlin/pmeet/pmeetserver/project/dto/response/SearchCompleteProjectResponseDto.kt
- src/main/kotlin/pmeet/pmeetserver/project/repository/CustomProjectRepository.kt
- src/main/kotlin/pmeet/pmeetserver/project/repository/CustomProjectRepositoryImpl.kt
- src/main/kotlin/pmeet/pmeetserver/project/repository/ProjectMemberRepository.kt
- src/main/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeService.kt
- src/main/kotlin/pmeet/pmeetserver/project/service/ProjectMemberService.kt
- src/main/kotlin/pmeet/pmeetserver/project/service/ProjectService.kt
- src/test/kotlin/pmeet/pmeetserver/project/ProjectIntegrationTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/repository/ProjectRepositoryUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeServiceUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/service/ProjectServiceUnitTest.kt
resolves #184 
완료된 프밋_메인 기획을 참고.
> ✨ feat: 완료된 프밋 목록 조회 기능 구현

- src/main/kotlin/pmeet/pmeetserver/project/controller/ProjectController.kt
- src/main/kotlin/pmeet/pmeetserver/project/dto/response/GetMyCompletedProjectResponseDto.kt
- src/main/kotlin/pmeet/pmeetserver/project/dto/response/ProjectMemberInfoDto.kt
- src/main/kotlin/pmeet/pmeetserver/project/repository/CustomProjectRepository.kt
- src/main/kotlin/pmeet/pmeetserver/project/repository/CustomProjectRepositoryImpl.kt
- src/main/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeService.kt
- src/main/kotlin/pmeet/pmeetserver/project/service/ProjectService.kt
- src/main/kotlin/pmeet/pmeetserver/user/controller/ResumeController.kt
- src/main/kotlin/pmeet/pmeetserver/user/domain/resume/Resume.kt
- src/main/kotlin/pmeet/pmeetserver/user/repository/resume/CustomResumeRepository.kt
- src/main/kotlin/pmeet/pmeetserver/user/repository/resume/CustomResumeRepositoryImpl.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/resume/ResumeFacadeService.kt
- src/main/kotlin/pmeet/pmeetserver/user/service/resume/ResumeService.kt
- src/test/kotlin/pmeet/pmeetserver/project/ProjectIntegrationTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/controller/ProjectControllerUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/repository/ProjectRepositoryUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeServiceUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/project/service/ProjectServiceUnitTest.kt
- src/test/kotlin/pmeet/pmeetserver/user/resume/service/ResumeFacadeServiceUnitTest.kt
[feat: 마이페이지 - 마이 프로젝트 - 완료된 프로젝트 조회](https://github.com/PmeetLabs/pmeet-server/commit/7a868b815c07322f2607e25a5c34e71640503e67)
[fix: 이력서 필터 조회 필수 조건 제거](https://github.com/PmeetLabs/pmeet-server/commit/dcce60988a78ef119b9ae0b96bf8bf3434f0af48)
> 🚀 deploy 2024.11.22 no.1
