PmeetLabs/pmeet-server

src/main/kotlin/pmeet/pmeetserver/user/dto/UserResponseDto.kt
UserResponseDto의 PassWord Field 제거
- 
-
=> chore: 유저 정보 응답에서 패스워드 필드 제거

src/main/kotlin/pmeet/pmeetserver/user/controller/UserController.kt, src/main/kotlin/pmeet/pmeetserver/user/dto/request/CheckNickNameRequestDto.kt, src/main/kotlin/pmeet/pmeetserver/user/service/UserFacadeService.kt, src/main/kotlin/pmeet/pmeetserver/user/service/UserService.kt
resolves #12
- Json Body에 담고자 PostMapping 사용
- 재사용성을 위해 getUserByNickName() 메서드 자체에서 익셉션을 던지지 않게함
=> feat: 닉네임 중복 체크

.gitignore, build.gradle.kts, src/main/kotlin/pmeet/pmeetserver/auth/service/EmailService.kt, src/main/kotlin/pmeet/pmeetserver/common/generator/VerificationCodeGenerator.kt, src/main/kotlin/pmeet/pmeetserver/config/CoroutineConfig.kt, src/main/kotlin/pmeet/pmeetserver/user/controller/AuthController.kt, src/main/kotlin/pmeet/pmeetserver/user/dto/request/SendVerificationCodeRequestDto.kt, src/main/kotlin/pmeet/pmeetserver/user/service/UserFacadeService.kt, src/main/resources/application.yml
resolves #9 
- 인증 코드 전송 후 Redis에 (email, verificationCode) 로 저장 
- TTL은 5분
- 민감 정보 유출 방지를 위해 yml 분리 후 gitignore 추가
=> feat: 인증 코드 이메일 전송

build.gradle.kts, src/main/kotlin/pmeet/pmeetserver/auth/service/EmailService.kt, src/main/kotlin/pmeet/pmeetserver/common/ErrorCode.kt, src/main/kotlin/pmeet/pmeetserver/config/MailConfig.kt, src/main/kotlin/pmeet/pmeetserver/user/controller/AuthController.kt, src/main/kotlin/pmeet/pmeetserver/user/dto/request/VerifyVerificationCodeRequestDto.kt, src/main/kotlin/pmeet/pmeetserver/user/service/UserFacadeService.kt
resolves #11 
- 이메일로 redis에 조회하여 인증 코드 매칭
- redis 조회 결과가 null이면 인증 시간 만료 예외
- yml 파일 분리로 인해 JavaMailSender Bean을 런타임 전에 생성하지 못해 직접 Bean으로 등록
- application-secret.yml 수정
- M1 MacBook 이상에서 발생하는 예외(런타임에 지장X) 제거를 위해 의존성 추가
=> feat: 이메일 인증 코드 확인

src/main/kotlin/pmeet/pmeetserver/common/ErrorCode.kt, src/main/kotlin/pmeet/pmeetserver/user/service/UserFacadeService.kt, src/main/kotlin/pmeet/pmeetserver/user/service/UserService.kt
getUser 관련 메서드 재사용성과 메서드의 책임을 고려한 refactoring
- UserFacadeService에서 EntityNotFoundException을 던지면 매번 유저를 불러올 때 Facade에서 EntityNotFoundException관련 코드를 작성해야 함 -> 이 책임을 UserService에게 이관
=> refac: getuser method 재사용을 위한 refactoring

src/main/resources/application.yml
- AWS EC2에 컨테이너 형식으로 띄움
- Mongo Replica Set에서 27017 포트를 사용하는 컨테이너가 Primary가 되도록 우선순위 변경하였음
- 
-
=> chore: 클라우드 환경에 Mongo, Redis 구축

build.gradle.kts, src/main/kotlin/pmeet/pmeetserver/auth/service/oauth/GoogleOauthService.kt, src/main/kotlin/pmeet/pmeetserver/auth/service/oauth/KakaoOauthService.kt, src/main/kotlin/pmeet/pmeetserver/auth/service/oauth/NaverOauthService.kt, src/main/kotlin/pmeet/pmeetserver/auth/service/oauth/OauthFacadeService.kt, src/main/kotlin/pmeet/pmeetserver/config/MongoConfig.kt, src/main/kotlin/pmeet/pmeetserver/config/WebClientConfig.kt, src/main/kotlin/pmeet/pmeetserver/user/controller/AuthController.kt, src/main/kotlin/pmeet/pmeetserver/user/domain/User.kt, src/main/kotlin/pmeet/pmeetserver/user/dto/UserInfo.kt, src/main/kotlin/pmeet/pmeetserver/user/repository/UserRepository.kt, src/main/kotlin/pmeet/pmeetserver/user/service/UserService.kt, src/main/resources/application.yml
resolves #20 #21 #22
- 구글,네이버,카카오 Oauth 추가
- DB에 User가 존재하면 JWT 토큰 발급
- 없으면 DB에 User save 후 JWT 토큰 발급
- 닉네임 부여 로직
- "Pmeet#{숫자4자리}"
- 랜덤 부여 할 경우 유저가 많아지면 중복 처리로 인한 리소스 낭비
- User엔티티에 nicknameNumber를 추가하여 새로운 User 저장 시 가장 큰 nicknameNumber를 가져와서 + 1을함
- "Pmeet#0001" -> "Pmeet#0002" -> "Pmeet#0003" ->->-> "Pmeet#9999"
- 
-
=> feat: O-Auth 로그인 기능 구현

build.gradle.kts, src/main/kotlin/pmeet/pmeetserver/auth/service/EmailService.kt, src/main/kotlin/pmeet/pmeetserver/common/ErrorCode.kt, src/main/kotlin/pmeet/pmeetserver/user/service/UserFacadeService.kt
resolves #35 
- 인증코드 매칭 시 redis에 저장
- TTL은 5분
- 코틀린의 스코프를 활용해 리팩터링
- security test 의존성 수정
=> feat: 이메일 인증 완료 여부를 체크하는 기능

build.gradle.kts, src/test/kotlin/pmeet/pmeetserver/auth/service/EmailServiceUnitTest.kt
- Kotest Describe Spec 적용
- 테스트를 위한 의존성 추가
- 테스트 실행 시 발생하는 Warn 해결 https://github.com/mockito/mockito/issues/3037 참고
- Dispatcher.IO Context대신 테스트용 Dispatcher를 테스트 시 Main으로 셋팅
- 테스트 방식은 https://techblog.woowahan.com/5825/ , https://developer.android.com/kotlin/coroutines/test?hl=ko#injecting-test-dispatchers 참고
=> test: 이메일 서비스 단위 테스트

build.gradle.kts, src/main/kotlin/pmeet/pmeetserver/auth/service/EmailService.kt, src/main/kotlin/pmeet/pmeetserver/common/generator/VerificationCodeGenerator.kt, src/main/kotlin/pmeet/pmeetserver/config/AwsS3Config.kt, src/main/kotlin/pmeet/pmeetserver/file/controller/FileController.kt, src/main/kotlin/pmeet/pmeetserver/file/dto/response/FileUrlResponseDto.kt, src/main/kotlin/pmeet/pmeetserver/file/service/FileService.kt
resolves #15 
- 서버리스 presingedUrl 방식의 업로드 다운로드
- 파일 저장 Path는 YYYY-MM-DD/domain/filename
- 다운로드는 Path 전체를 포함한 ObjectName을 파라미터로 받음
- presingedUrl의 유효 기간은 30분
=> feat: aws S3 presigned-URL

src/main/kotlin/pmeet/pmeetserver/user/controller/AuthController.kt
resolves #67 
- google, naver, kakao 모두 dto를 반환하는게 아니라 localhost:3000 으로 토큰 및 유저ID를 쿼리파라미터로 담아서 redirect
-
=> fix: Oauth API Reponse 수정

build.gradle.kts, src/test/kotlin/pmeet/pmeetserver/ProjectConfig.kt, src/test/kotlin/pmeet/pmeetserver/auth/service/EmailServiceUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/user/controller/UserControllerUnitTest.kt
- mockkbean 사용을 위해 springmockk의존성 추가
- test에서 webtestClient 자동 주입이 되지 않아 SpringExtension 의존성과 object 추가
- withMockUser를 사용할 수 없어 UsernamePasswordAuthenticationToken를 mockAuthentication에 추가
=> test: 유저 컨트롤러 단위 테스트

src/main/kotlin/pmeet/pmeetserver/common/ErrorCode.kt, src/main/kotlin/pmeet/pmeetserver/common/utils/page/SliceResponse.kt, src/main/kotlin/pmeet/pmeetserver/user/controller/JobController.kt, src/main/kotlin/pmeet/pmeetserver/user/domain/job/Job.kt, src/main/kotlin/pmeet/pmeetserver/user/dto/job/request/CreateJobRequestDto.kt, src/main/kotlin/pmeet/pmeetserver/user/dto/job/response/JobResponseDto.kt, src/main/kotlin/pmeet/pmeetserver/user/repository/job/CustomJobRepository.kt, src/main/kotlin/pmeet/pmeetserver/user/repository/job/CustomJobRepositoryImpl.kt, src/main/kotlin/pmeet/pmeetserver/user/repository/job/JobRepository.kt, src/main/kotlin/pmeet/pmeetserver/user/service/job/JobFacadeService.kt, src/main/kotlin/pmeet/pmeetserver/user/service/job/JobService.kt, src/test/kotlin/pmeet/pmeetserver/config/MongoTestConfig.kt, src/test/kotlin/pmeet/pmeetserver/user/job/JobIntegrationTest.kt, src/test/kotlin/pmeet/pmeetserver/user/job/controller/JobControllerUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/user/job/repository/JobRepositoryUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/user/job/service/JobFacadeServiceUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/user/job/service/JobServiceUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/util/RestPageImpl.kt, src/test/kotlin/pmeet/pmeetserver/util/RestSliceImpl.kt
resolves #56 
- 직무를 따로 조회하는 경우가 있어 Embedding 스키마를 사용하지 않았음
- Aggregation을 작성하기 위해 JobCustomRepo 추가
- JobRepo 단위테스트에 template으로 JobCustomRepo 생성 후 factort로 JobRepo생성시 추가
- Flux를 Slice로 변환하는 로직을 SliceResponse의 정적 메서드 of로 추출
- 정렬 규칙은 1순위 직무이름 길이 오름차순 , 2순위 직무이름 오름차순
- 입력으로 들어온 이름이 null인 경우 전체 기준 페이징
- 테스트에서 역직렬화를 위한 RestPageImpl, RestSliceImpl 추가
- 통합테스트시 ReactiveMongoTemplate Bean이 2개라서 Test용 Template에 Primary추가
=> feat: 직무 생성 및 이름으로 직무 검색

src/main/kotlin/pmeet/pmeetserver/common/ErrorCode.kt, src/main/kotlin/pmeet/pmeetserver/user/controller/ResumeController.kt, src/main/kotlin/pmeet/pmeetserver/user/domain/resume/Resume.kt, src/main/kotlin/pmeet/pmeetserver/user/dto/resume/request/CreateResumeRequestDto.kt, src/main/kotlin/pmeet/pmeetserver/user/dto/resume/request/DeleteResumeRequestDto.kt, src/main/kotlin/pmeet/pmeetserver/user/dto/resume/request/UpdateResumeRequestDto.kt, src/main/kotlin/pmeet/pmeetserver/user/dto/resume/response/ResumeResponseDto.kt, src/main/kotlin/pmeet/pmeetserver/user/repository/resume/ResumeRepository.kt, src/main/kotlin/pmeet/pmeetserver/user/service/resume/ResumeFacadeService.kt, src/main/kotlin/pmeet/pmeetserver/user/service/resume/ResumeService.kt, src/test/kotlin/pmeet/pmeetserver/user/resume/ResumeGenerator.kt, src/test/kotlin/pmeet/pmeetserver/user/resume/ResumeIntegrationTest.kt, src/test/kotlin/pmeet/pmeetserver/user/resume/controller/ResumeControllerUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/user/resume/repository/ResumeRepositoryUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/user/resume/service/ResumeFacadeServiceUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/user/resume/service/ResumeServiceUnitTest.kt
- #59 
- resolves #60 
- 🐛 fix: 이력서 업데이트 시, user Id 도 업데이트 조건으로 사용하며, 요청 사용자의 id 로 수정 권한 검증
- ✨ feat: 이력서 삭제 요청 기능 구현
- ♻️ refactor: pr review 반영
=> 🐛 fix: 이력서 업데이트 로직 변경 & ✨ feat: 이력서 삭제 요청 기능 구현

src/main/kotlin/pmeet/pmeetserver/project/controller/ProjectController.kt, src/main/kotlin/pmeet/pmeetserver/project/domain/Project.kt, src/main/kotlin/pmeet/pmeetserver/project/dto/request/CreateProjectRequestDto.kt, src/main/kotlin/pmeet/pmeetserver/project/dto/request/ProjectCommonRequestDto.kt, src/main/kotlin/pmeet/pmeetserver/project/dto/response/ProjectResponseDto.kt, src/main/kotlin/pmeet/pmeetserver/project/repository/ProjectRepository.kt, src/main/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeService.kt, src/main/kotlin/pmeet/pmeetserver/project/service/ProjectService.kt, src/main/kotlin/pmeet/pmeetserver/project/validation/DateRangeValidator.kt, src/main/kotlin/pmeet/pmeetserver/project/validation/TotalSumMaxValidator.kt, src/main/kotlin/pmeet/pmeetserver/project/validation/annotation/TotalSumMax.kt, src/main/kotlin/pmeet/pmeetserver/project/validation/annotation/ValidDateRange.kt, src/main/kotlin/pmeet/pmeetserver/user/controller/JobController.kt, src/test/kotlin/pmeet/pmeetserver/project/ProjectIntegrationTest.kt, src/test/kotlin/pmeet/pmeetserver/project/controller/ProjectControllerUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeServiceUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/project/service/ProjectServiceUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/user/job/controller/JobControllerUnitTest.kt
resolves #96 
- DTO에 검증이 필요한 커스텀 검증 어노테이션 생성 (종료일 시작일 검증, 하위 DTO List의 Number Sum 검증)
- Project 도메인에 북마크 기능을 위한 참조 타입 UserId를 List로 가지게 하였음
- 직무 컨트롤러에 누락된 `@Valid` 어노테이션 추가
- 직무 컨트롤러 유닛 테스트에서 search의 인증 권한이 없는 경우에 대한 테스트 수정
=> feat: 프밋 모집 게시물 등록

src/main/kotlin/pmeet/pmeetserver/common/ErrorCode.kt, src/main/kotlin/pmeet/pmeetserver/common/exception/ExceptionDto.kt, src/main/kotlin/pmeet/pmeetserver/common/exception/ForbiddenRequestException.kt, src/main/kotlin/pmeet/pmeetserver/common/exception/GlobalExceptionHandler.kt, src/main/kotlin/pmeet/pmeetserver/user/service/resume/ResumeFacadeService.kt, src/test/kotlin/pmeet/pmeetserver/user/resume/service/ResumeFacadeServiceUnitTest.kt
- 권한 없음(403) 을 나타내는 `ForbiddenRequestException` 추가
- `ForbiddenRequestException` Handler 추가
- ErrorCode의 Code가 400인 것들을 세분화
- ErrorCode의 Enum 이름 대신 Code 필드를 반환하게 수정(이미지 확인)
- Before ![image](https://github.com/user-attachments/assets/5c596a41-d910-4f20-8cdd-c980d01fcfe9)
- After ![image](https://github.com/user-attachments/assets/30aaa2d1-2a63-47f5-a384-681a44dfddbc)
=> refac: ForbiddenRequestException 추가 및 ErrorCode 디테일 분류

src/main/kotlin/pmeet/pmeetserver/file/dto/response/FileUrlResponseDto.kt, src/main/kotlin/pmeet/pmeetserver/file/service/FileService.kt
- 클라이언트에서 ObjectName을 알 수가 없는 문제가 있어 응답 수정
- Response에 ObjectName 필드 추가
=> fix: 파일 업로드 및 다운로드 응답에 ObjectName 추가

src/main/kotlin/pmeet/pmeetserver/common/ErrorCode.kt, src/main/kotlin/pmeet/pmeetserver/project/controller/ProjectController.kt, src/main/kotlin/pmeet/pmeetserver/project/domain/Project.kt, src/main/kotlin/pmeet/pmeetserver/project/dto/request/UpdateProjectRequestDto.kt, src/main/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeService.kt, src/main/kotlin/pmeet/pmeetserver/project/service/ProjectService.kt, src/test/kotlin/pmeet/pmeetserver/project/ProjectIntegrationTest.kt, src/test/kotlin/pmeet/pmeetserver/project/controller/ProjectControllerUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeServiceUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/project/service/ProjectServiceUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/user/resume/service/ResumeServiceUnitTest.kt
resolves #99 
resolves #97 
- `Project` 객체의 필드를 수정하는 `update` 메서드
-  북마크, 완료여부는 분리된 API로 수정될 예정으로 도메인 `update` 메서드에서 제외
- `getProjectById` 테스트가 없어서 추가 
- `ResumeServiceUnitTest`에 불 필요한 모킹 제거
-  통합 테스트에서 `Project` 생성자에 id 추가
- UpdatedAt 추가
=> feat: 프밋 모집 게시글 수정, 프밋 모집 게시글 UpdatedAt 추가

src/main/kotlin/pmeet/pmeetserver/common/ErrorCode.kt, src/main/kotlin/pmeet/pmeetserver/project/controller/ProjectController.kt, src/main/kotlin/pmeet/pmeetserver/project/repository/ProjectCommentRepository.kt, src/main/kotlin/pmeet/pmeetserver/project/service/ProjectCommentService.kt, src/main/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeService.kt, src/main/kotlin/pmeet/pmeetserver/project/service/ProjectService.kt, src/test/kotlin/pmeet/pmeetserver/project/ProjectIntegrationTest.kt, src/test/kotlin/pmeet/pmeetserver/project/controller/ProjectControllerUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/project/repository/ProjectCommentRepositoryUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/project/service/ProjectCommentServiceUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeServiceUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/project/service/ProjectServiceUnitTest.kt
resolves #98 
- 영구삭제 기능으로 개발
- 게시글에 달린 댓글도 함께 삭제
- 
-
=> feat: 프밋 모집 게시글 영구 삭제

src/main/kotlin/pmeet/pmeetserver/project/controller/ProjectController.kt, src/main/kotlin/pmeet/pmeetserver/project/domain/Project.kt, src/main/kotlin/pmeet/pmeetserver/project/dto/request/SearchProjectRequestDto.kt, src/main/kotlin/pmeet/pmeetserver/project/dto/response/ProjectResponseDto.kt, src/main/kotlin/pmeet/pmeetserver/project/dto/response/SearchProjectResponseDto.kt, src/main/kotlin/pmeet/pmeetserver/project/enums/ProjectFilterType.kt, src/main/kotlin/pmeet/pmeetserver/project/enums/ProjectSortProperty.kt, src/main/kotlin/pmeet/pmeetserver/project/repository/CustomProjectRepository.kt, src/main/kotlin/pmeet/pmeetserver/project/repository/CustomProjectRepositoryImpl.kt, src/main/kotlin/pmeet/pmeetserver/project/repository/ProjectRepository.kt, src/main/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeService.kt, src/main/kotlin/pmeet/pmeetserver/project/service/ProjectService.kt, src/test/kotlin/pmeet/pmeetserver/project/ProjectIntegrationTest.kt, src/test/kotlin/pmeet/pmeetserver/project/controller/ProjectControllerUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/project/repository/ProjectRepositoryUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeServiceUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/project/service/ProjectServiceUnitTest.kt
resolves #95
resolves #94
- 직무`or`타이틀(ALL), 타이틀, 직무이름을 필터타입으로 사용
- 완료된 게시글도 조회하는 경우를 대비하여 `isCompleted`도 필터 추가
- 정렬 규칙은 인기순, 최신등록순, 수정순이 있음
- 북마크한 유저ID는 read-only가 아니므로 `MutableList`로 변경
=> feat: 프밋 모집 게시글 필터 슬라이스 조회

src/main/kotlin/pmeet/pmeetserver/project/controller/ProjectController.kt, src/main/kotlin/pmeet/pmeetserver/project/domain/Project.kt, src/main/kotlin/pmeet/pmeetserver/project/dto/response/ProjectResponseDto.kt, src/main/kotlin/pmeet/pmeetserver/project/dto/response/SearchProjectResponseDto.kt, src/main/kotlin/pmeet/pmeetserver/project/enums/ProjectSortProperty.kt, src/main/kotlin/pmeet/pmeetserver/project/repository/CustomProjectRepositoryImpl.kt, src/main/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeService.kt, src/test/kotlin/pmeet/pmeetserver/project/ProjectIntegrationTest.kt, src/test/kotlin/pmeet/pmeetserver/project/controller/ProjectControllerUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/project/repository/ProjectRepositoryUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeServiceUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/project/service/ProjectServiceUnitTest.kt
resolves #104 
- **쿠팡의 상품 좋아요 기능을 참고하여** 북마크 기능이 멱등하게 동작하도록 하였고, Post 대신 Put 사용 
- 북마크 추가 요청을 여러번 보내면 추가 시간만 갱신함
- 통일성을 위해 카멜 케이스 였던 `bookMark`를 `bookmark`로 변경
-
=> feat: 프밋 모집 게시글 북마크 on/off

src/main/kotlin/pmeet/pmeetserver/project/repository/CustomProjectRepositoryImpl.kt
`{ "aggregate" : "__collection__", "pipeline" : [{ "$match" : { "isCompleted" : false, "$and" : [{}]}}, { "$addFields" : { "bookmarkersSize" : { "$size" : "$bookmarkers"}}}, { "$sort" : { "updatedAt" : -1}}, { "$skip" : 0}, { "$limit" : 9}]}`
**The argument to $size must be an array, but was of type: missing'**
에러 발생하여 Null 인 케이스 로직 추가
- 
-
=> fix: 북마크 리스트 사이즈 Null 핸들링

src/main/kotlin/pmeet/pmeetserver/file/service/FileFacadeService.kt, src/main/kotlin/pmeet/pmeetserver/file/service/FileService.kt
- 파일 이름이 빈 문자열인 경우 FileService에서 Exception이 발생하는 문제를 Null을 반환하도록 하여 해결
=> fix: 빈 문자열의 파일 이름의 경우 FileService에서 발생하는 예외 방지

src/main/kotlin/pmeet/pmeetserver/common/ErrorCode.kt, src/main/kotlin/pmeet/pmeetserver/project/controller/ProjectMemberController.kt, src/main/kotlin/pmeet/pmeetserver/project/controller/ProjectTryoutController.kt, src/main/kotlin/pmeet/pmeetserver/project/domain/ProjectMember.kt, src/main/kotlin/pmeet/pmeetserver/project/domain/ProjectTryout.kt, src/main/kotlin/pmeet/pmeetserver/project/dto/tryout/request/PatchProjectTryoutRequestDto.kt, src/main/kotlin/pmeet/pmeetserver/project/repository/ProjectMemberRepository.kt, src/main/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeService.kt, src/main/kotlin/pmeet/pmeetserver/project/service/ProjectMemberService.kt, src/main/kotlin/pmeet/pmeetserver/project/service/ProjectTryoutService.kt, src/test/kotlin/pmeet/pmeetserver/project/ProjectMemberIntegrationTest.kt, src/test/kotlin/pmeet/pmeetserver/project/ProjectTryoutIntegrationTest.kt, src/test/kotlin/pmeet/pmeetserver/project/controller/ProjectMemberControllerUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/project/controller/ProjectTryoutControllerUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeServiceUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/project/service/ProjectMemberServiceUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/project/service/ProjectTryoutServiceUnitTest.kt
resolves #130 
✨ feat: 프밋 지원 현황 상태 변경 기능 구현
- ♻️ refactor: ProjectFacadeService 에서 project cud 권한 확인하는 로직 분리
- ✨ feat: 프밋 지원 현황 상태 변경 기능 구현
- ✨ feat: 프밋 멤버 내보내기 기능 구현
=> ✨ feat: 프밋 지원 현황 상태 변경 기능 구현

src/main/kotlin/pmeet/pmeetserver/project/controller/ProjectController.kt, src/main/kotlin/pmeet/pmeetserver/project/dto/comment/ProjectCommentWithChildDto.kt, src/main/kotlin/pmeet/pmeetserver/project/dto/comment/response/GetProjectCommentResponseDto.kt, src/main/kotlin/pmeet/pmeetserver/project/dto/comment/response/GetProjectCommentWithChildResponseDto.kt, src/main/kotlin/pmeet/pmeetserver/project/repository/ProjectCommentRepositoryCustom.kt, src/main/kotlin/pmeet/pmeetserver/project/repository/ProjectCommentRepositoryCustomImpl.kt, src/main/kotlin/pmeet/pmeetserver/project/service/ProjectCommentService.kt, src/main/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeService.kt, src/test/kotlin/pmeet/pmeetserver/project/ProjectIntegrationTest.kt, src/test/kotlin/pmeet/pmeetserver/project/controller/ProjectControllerUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/project/service/ProjectCommentServiceUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeServiceUnitTest.kt
resolves #152 
댓글 조회 시 유저 닉네임, 프로필 이미지 url 추가
- Repository의 Return을 ResponseDto -> Dto로 변경
- Facade Service에서 Dto를 ResponseDto로 변경 (여기서 UserService를 활용하여 objectname 추출)
- 댓글 생성 시 parentCommentId가 주어질 시 검증 로직 추가
=> feat: 댓글에 유저 닉네임, 프로필 이미지 url 추가

src/main/kotlin/pmeet/pmeetserver/user/controller/ResumeController.kt, src/main/kotlin/pmeet/pmeetserver/user/dto/resume/response/SearchedResumeResponseDto.kt, src/main/kotlin/pmeet/pmeetserver/user/repository/resume/CustomResumeRepository.kt, src/main/kotlin/pmeet/pmeetserver/user/repository/resume/CustomResumeRepositoryImpl.kt, src/main/kotlin/pmeet/pmeetserver/user/service/resume/ResumeFacadeService.kt, src/main/kotlin/pmeet/pmeetserver/user/service/resume/ResumeService.kt, src/test/kotlin/pmeet/pmeetserver/user/resume/controller/ResumeControllerUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/user/resume/repository/ResumeRepositoryUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/user/resume/service/ResumeFacadeServiceUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/user/resume/service/ResumeServiceUnitTest.kt
resolves #168 
- 이력서 목록 조회 시, 본인의 이력서를 제외하는 조건을 추가
- book 수와 bookmark 여부 필드 추가
- ✨ feat: 이력서 조건 목록 조회 결과에 나의 이력서는 제외된다.
- ✨ feat: 이력서 조건 목록 조회 결과에, 총 bookmark 수와 검색자 bookmark 여부 필드 추가
=> ✨ feat: 이력서 조건 목록 조회 결과에 필드 및 값 수정

src/main/kotlin/pmeet/pmeetserver/common/generator/AggregationGenerator.kt, src/test/kotlin/pmeet/pmeetserver/user/job/repository/JobRepositoryUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/user/techStack/repository/TechStackRepositoryUnitTest.kt
- UX 향상을 위해 대문자 조건 제거
✨ feat: 직무 및 기술 스택 검색 시, 대소문자 구분 조건 제거
=> ✨ feat: 직무 및 기술 스택 검색 시, 대소문자 구분 조건 제거

src/main/kotlin/pmeet/pmeetserver/user/controller/NotificationController.kt, src/main/kotlin/pmeet/pmeetserver/user/domain/notification/Notification.kt, src/main/kotlin/pmeet/pmeetserver/user/repository/notification/CustomNotificationRepository.kt, src/main/kotlin/pmeet/pmeetserver/user/repository/notification/CustomNotificationRepositoryImpl.kt, src/main/kotlin/pmeet/pmeetserver/user/repository/notification/NotificationRepository.kt, src/main/kotlin/pmeet/pmeetserver/user/service/notification/NotificationService.kt, src/test/kotlin/pmeet/pmeetserver/user/notification/NotificationIntegrationTest.kt, src/test/kotlin/pmeet/pmeetserver/user/notification/controller/NotificationControllerUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/user/notification/repository/NotificationRepositoryUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/user/notification/service/NotificationServiceUnitTest.kt
resolves #173 
resolves #132 
✨ feat: SSE 를 이용한 알림 수신 기능 구현
- 알림 객체는 서버 내 여러 이벤트로 인해서 생성이 됩니다.
- 생성된 알림 객체는 mongo DB 에 저장됩니다.
- DB 에 저장과 동시에 emitter 를 통해서 이벤트로 생성이 됩니다.
- 이벤트에 대한 구독자가 있다면 이벤트를 송신합니다.
=> ✨ feat: SSE 를 이용한 알림 수신 기능 구현

src/main/kotlin/pmeet/pmeetserver/user/controller/AuthController.kt, src/test/kotlin/pmeet/pmeetserver/user/controller/AuthControllerUnitTest.kt
- 암묵적 승인 방식은 백엔드 서버 인증 없이 동작하기 때문에 만료 기간이 긴 Refresh Token은 오용 가능성이 있음
- Redirect URL 에서 Refresh Token 제거
=> fix: 암묵적 승인 방식 OAuth RedirectURL에서 Refresh Token 제거

src/main/kotlin/pmeet/pmeetserver/file/service/FileService.kt, src/main/kotlin/pmeet/pmeetserver/user/controller/ResumeController.kt, src/main/kotlin/pmeet/pmeetserver/user/domain/resume/Resume.kt, src/main/kotlin/pmeet/pmeetserver/user/dto/resume/request/CreateResumeRequestDto.kt, src/main/kotlin/pmeet/pmeetserver/user/dto/resume/request/UpdateResumeRequestDto.kt, src/main/kotlin/pmeet/pmeetserver/user/dto/resume/response/ResumeResponseDto.kt, src/main/kotlin/pmeet/pmeetserver/user/service/resume/ResumeFacadeService.kt, src/test/kotlin/pmeet/pmeetserver/user/resume/ResumeGenerator.kt, src/test/kotlin/pmeet/pmeetserver/user/resume/ResumeIntegrationTest.kt, src/test/kotlin/pmeet/pmeetserver/user/resume/controller/ResumeControllerUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/user/resume/repository/ResumeRepositoryUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/user/resume/service/ResumeFacadeServiceUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/user/resume/service/ResumeServiceUnitTest.kt
- 기획 상 포트폴리오 파일은 여러개 가능
- 요청 DTO에서의 portfolioFileUrls은 Null을 허용하지 않으며, 빈 배열은 허용한다.
- 응답 DTO에서 portfolioFileUrls는 Null을 허용한다.
- Document에서 portfolioFileUrls는 Null을 허용하지 않으며, 빈 배열은 허용한다.
- 여러개의 objectName을 다루는 generatePreSignedUrlsToDownload 메서드 추가
- DTO의 portfolioFileUrl를 portfolioFileUrls로 변경
=> fix: 이력서 포트폴리오 파일 업로드 여러개 가능 하도록 수정

src/main/kotlin/pmeet/pmeetserver/project/controller/ProjectController.kt, src/main/kotlin/pmeet/pmeetserver/project/dto/response/GetMyInReviewProjectResponseDto.kt, src/main/kotlin/pmeet/pmeetserver/project/repository/CustomProjectRepository.kt, src/main/kotlin/pmeet/pmeetserver/project/repository/CustomProjectRepositoryImpl.kt, src/main/kotlin/pmeet/pmeetserver/project/repository/vo/ProjectWithProjectTryout.kt, src/main/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeService.kt, src/main/kotlin/pmeet/pmeetserver/project/service/ProjectService.kt, src/test/kotlin/pmeet/pmeetserver/project/ProjectIntegrationTest.kt, src/test/kotlin/pmeet/pmeetserver/project/controller/ProjectControllerUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/project/repository/ProjectRepositoryUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeServiceUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/project/service/ProjectServiceUnitTest.kt
resolves #187 
- ProjectWithTryout VO를 사용해 projectRepository에서 project와 ProjectTryOut lookup한 결과 저장
- 테스트에서 다운로드 URL 이터레이터 문제 수정
=> feat: 마이페이지 - 마이프로젝트 - 지원한 프로젝트 조회 기능

src/main/kotlin/pmeet/pmeetserver/project/controller/ProjectController.kt, src/main/kotlin/pmeet/pmeetserver/project/dto/response/GetMyCompletedProjectResponseDto.kt, src/main/kotlin/pmeet/pmeetserver/project/dto/response/ProjectMemberInfoDto.kt, src/main/kotlin/pmeet/pmeetserver/project/repository/CustomProjectRepository.kt, src/main/kotlin/pmeet/pmeetserver/project/repository/CustomProjectRepositoryImpl.kt, src/main/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeService.kt, src/main/kotlin/pmeet/pmeetserver/project/service/ProjectService.kt, src/test/kotlin/pmeet/pmeetserver/project/ProjectIntegrationTest.kt, src/test/kotlin/pmeet/pmeetserver/project/controller/ProjectControllerUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/project/repository/ProjectRepositoryUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/project/service/ProjectFacadeServiceUnitTest.kt, src/test/kotlin/pmeet/pmeetserver/project/service/ProjectServiceUnitTest.kt
resolves #189 
- 기존의 findProjectsByProjectMemberUserIdAndIsCompletedOrderByCreatedAtDesc와는 Sort 적용 순서가 달라서 분리
- 
-
=> feat: 마이페이지 - 마이 프로젝트 - 완료된 프로젝트 조회
